# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b8a24631307677982333100e2878c0040526dff85d53a8c01d9ca32111427fcf1c9397697cd161f137c8e0fb0d162616c769365478b127340a09e4fb5b4f5c3

test:
  secret_key_base: 4f871165f9019e5d65af727009934fb890f4740b82ac5b338e5266dffb1cc16bd5a0f8e5d1675cd7269d5242aafe04e2c73aef42d7a9c70d5b7deaf56a14cd6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
